module "role_base" {
  source  = "terraform-google-modules/iam/google//modules/custom_role_iam"
  version = "~> 7.7.1"

  target_level = "org"
  target_id    = var.organization_id
  role_id      = "base"
  title        = "Base"
  description  = "Role given to all users in the organization"
  permissions = [
    "essentialcontacts.contacts.get",
    "essentialcontacts.contacts.list",
    "orgpolicy.constraints.list",
    "orgpolicy.policies.list",
    "orgpolicy.policy.get",
    "resourcemanager.folders.get",
    "resourcemanager.folders.list",
    "resourcemanager.projects.get",
    "resourcemanager.projects.list",
    "resourcemanager.organizations.get",
    "monitoring.timeSeries.list",
    "serviceusage.operations.get",
    "serviceusage.operations.list",
    "serviceusage.services.get",
    "serviceusage.services.list",
    "serviceusage.quotas.get",
    "serviceusage.quotas.update",
    "cloudasset.assets.searchAllResources",
    "cloudsupport.properties.get",
    "cloudsupport.techCases.create",
    "cloudsupport.techCases.escalate",
    "cloudsupport.techCases.get",
    "cloudsupport.techCases.list",
    "cloudsupport.techCases.update",
    "container.clusters.get",
    "container.clusters.list",
    "container.cronJobs.get",
    "container.cronJobs.list",
    "container.deployments.get",
    "container.deployments.list",
    "container.events.get",
    "container.events.list",
    "container.jobs.get",
    "container.jobs.list",
    "container.namespaces.get",
    "container.namespaces.list",
    "container.nodes.get",
    "container.nodes.list",
    "container.persistentVolumeClaims.get",
    "container.persistentVolumeClaims.list",
    "container.persistentVolumes.get",
    "container.persistentVolumes.list",
    "container.pods.get",
    "container.pods.getLogs",
    "container.pods.list",
    "container.replicaSets.get",
    "container.replicaSets.list",
    "container.services.get",
    "container.services.list",
    "container.statefulSets.get",
    "container.statefulSets.list",
    "container.replicationControllers.get",
    "container.replicationControllers.list",
    "logging.logs.list",
    "logging.logServices.list",
    "logging.logMetrics.get",
    "logging.logMetrics.list",
    "logging.logEntries.list",
    "logging.logServiceIndexes.list",
    "logging.logEntries.download",
  ]
}
